Allowing file-specific transformation scripts
hiker/fab pull request #19
Opened 2024-04-30 02:15 UTC by jasonjunweilyu

This pull request is related to Issue #18. The purpose is to allow each x90 file to have its specific transformation script. Two files have changed:
1. source/fab/steps/psyclone.py:

The `psyclone` function now takes in a function as the value for the `transformation_script` parameter. This input function will be written by the user to take in an x90 file path (parameter `fpath`), and return a transformation script path. 

2. tests/system_tests/psyclone/test_psyclone_system_test.py:

Tests are added to verify that the input transformation script function has taken in the x90 file path and returned a transformation script path, which is then passed successfully to the psyclone command with `-s`. The checking for the transformation_script_hash is modified as now the transformation_script_hash is calculated when processing each file.

2024-04-30 02:18 UTC, jasonjunweilyu commented
Taken back the ready-for-review as I found there is a unit test needs to be fixed.

2024-04-30 05:23 UTC, jasonjunweilyu commented
Now the mypy and flake8 issues are fixed. PSyclone unit test has been modified. This pull request is ready for review.

2024-05-02 03:06 UTC, hiker requested changes
Great job, thanks. I can't wait to see this merged in! There are a few minor comments, and one point to be discussed ;) Back to you for now.

2024-05-02 03:06 UTC, hiker commented on source/fab/steps/psyclone.py
> +    return analysed_x90, all_kernel_hashes
This is not your fault, but with your change, I wonder: do we actually still need this function? It now basically does one warning and two calls. The whole code might be easier to understand if this function would be removed, and the `prebuild_analyses` variable (which is now pair) is not used, instead _generate_mp_payload directly takes these two arguments?
That's more of a question than 'this needs to be changed' :)

2024-05-02 03:18 UTC, hiker commented
@jasonjunweilyu , sorry, I just realised I forgot two things:
it would be good to have a real example of this function in the run configs (`lfric/atm.py` and `lfric/gungho.py` seems to use a script), so you would have to update them, and include the proper function to use (i.e. a function that does the current Makefile behaviour - i.e. checks for a file-specific script, if not global.py, if not None).

Also, surprisingly there is no documentation on how to use PSyclone at all (only the PSyclone overrides in `doc/sources/advanced_config.rst). Can you add a section on how to use PSyclone to `doc/source/writing_config.rst`? Just link to the PSyclone github page for details, but describe how a PSyclone step is added, including an example of a transformation script (i.e. the one you have added to the run_configs above).

2024-05-02 23:57 UTC, jasonjunweilyu commented on tests/system_tests/psyclone/test_psyclone_system_test.py
> +        mock_transformation_script = mock.create_autospec(dummy_transformation_script, return_value=Path(__file__))
Thanks a lot. This is a great feature. I thought you have to define or import a function as a target for Mock to mock. But it turns out to be not the case.

2024-05-03 01:21 UTC, jasonjunweilyu commented on source/fab/steps/psyclone.py
> +    return analysed_x90, all_kernel_hashes
Thanks for pointing this out. `_analysis_for_prebuilds` does not seem to be necessary after my change. I have moved the two calls into the `psyclone` function. Hope this makes it easier to understand and the whole process more streamlined. The descriptions of `_analysis_for_prebuilds` are useful. So I copied the descriptions to either `_analyse_kernels` or `_gen_prebuild_hash`.

2024-05-03 09:43 UTC, jasonjunweilyu commented
Hi @hiker , I just finished making changes according to your comments. Now you can re-review my PR. Thanks.

2024-05-08 02:22 UTC, hiker requested changes
Great job, esp, the improved documentation. The main outstanding issue would be the example scripts (adding config as argument). So nearly there.

2024-05-09 05:14 UTC, jasonjunweilyu commented on docs/source/writing_config.rst
> +            You can pass in `common_flags` list as an argument.
No idea. I installed sphinx myself and tried rending with it. The rendered html shows the function names in bold. So I think the syntax is working.

2024-05-09 05:20 UTC, jasonjunweilyu commented on docs/source/writing_config.rst
> +            You can pass in kernel file roots to `kernel_roots`, a function to get transformation script to
It is a bullet list after rending.

2024-05-09 05:27 UTC, jasonjunweilyu commented on docs/source/writing_config.rst
> +After the psyclone step, you can find `_psy.f90` files in the `'build_output'` folder. There will be a collection
Thanks. I have changed this.

2024-05-09 05:28 UTC, jasonjunweilyu commented on docs/source/writing_config.rst
> +    :emphasize-lines: 8,18,19
The emphasis works on my own rendering with sphinx. So I think it should be fine

2024-05-10 01:26 UTC, jasonjunweilyu commented on run_configs/lfric/atm.py
> +    if global_transformation_script:
Thanks for the and explanation and suggestions. I was thinking of a scenario when different groups of x90 files need to use the same optimisation script for each group. So I actually coded for this scenario:

`global_transformation_script = '$source/optimisation/nci-gadi/global.py'`
`local_transformation_script = {'$source/algorithm/solver/*':"$source/optimisation/nci-gadi/local1.py",
                                       '$source/algorithm/galerkin*':'$source/optimisation/nci-gadi/local2.py',
                                       '$source/algorithm/sci*':'$source/optimisation/nci-gadi/local3.py',
                                       }`
 
The complex if-else logic is for finding match in the `local_transformation_script` dictionary.

Now it seems that each x90, if needing a special optimisation script, would have its unique optimisation script. Then the logic can be simplified a lot.

2024-05-10 01:29 UTC, jasonjunweilyu commented
Hi @hiker , I finished making modifications. Please review the changes when you have time. Thanks.

2024-05-13 04:32 UTC, hiker requested changes
Nearly there. I believe the examples need to be tested, and then I was motived to start nit-picking :)

2024-05-13 04:32 UTC, hiker commented on docs/source/writing_config.rst
> +            You can pass in `common_flags` list as an argument.
Thanks for testing. Stupid git :P

2024-05-13 04:32 UTC, hiker commented on run_configs/lfric/gungho.py
> +    if local_transformation_script:
Is this test actually correct? 
``` 
>>> p=Path("/does-not-exist")
>>> if p:
...    print(p)
... 
/does-not-exist
```
I.e. this tests only if `local_transformation_script` is empty, not if it exists. I believe this should be:
```
>>> if p.exists():
...     print(p)
... 
>>> 
```
I was about to say: add a test for this ... but this is just an example, so I don't think we should do this.

2024-05-13 04:32 UTC, hiker commented on run_configs/lfric/gungho.py
> +    global_transformation_script = config.source_root / 'lfric' / 'miniapps' / 'gungho_model' / 'optimisation' / \
Since I already had one comment that requires you to have a look: could you also specify the optimisation path only once? Ie. `opt_path=...`, and then use opt_path further down

2024-05-13 04:32 UTC, hiker commented on run_configs/lfric/gungho.py
> +    elif global_transformation_script:
Hmm - if `local_transformation_script` exist, we don't even have to define `global_transformation_script`. So could you move the assignment to `global_transformation_script` to between line 35 and 36 (and turn the elif into an if).
And then also replace the `else:\nreturn' with just a `return` (without the if) - pylint complains otherwise (admittedly we don't need to run pylint, so I tend to notice these things now :) )

2024-05-13 04:32 UTC, hiker commented on docs/source/writing_config.rst
> +            You can pass in kernel file roots to `kernel_roots`, a function to get transformation script to
I actually meant a  ... sub-bullet list, i.e. the 4 parameter that are listed here. TBH, just leave it the way it is, Matthew can add his opinion :)

2024-05-13 04:32 UTC, hiker commented on run_configs/lfric/atm.py
> +    if local_transformation_script:
Same changes as above.

2024-05-13 04:32 UTC, hiker commented on run_configs/lfric/atm.py
> +    if local_transformation_script:
Oops ... same changes as below :)

2024-05-13 05:00 UTC, jasonjunweilyu commented on run_configs/lfric/gungho.py
> +    if local_transformation_script:
Thanks a lot. I overlooked this one.

2024-05-13 05:00 UTC, jasonjunweilyu commented on run_configs/lfric/gungho.py
> +    elif global_transformation_script:
Thanks. The code is much neater after the change.

2024-05-13 05:11 UTC, jasonjunweilyu commented
Hi @hiker , thanks a lot for the suggestions. It is not nit-picking. They all made the codes and docs better. I have modified accordingly.

2024-05-15 00:19 UTC, hiker commented on tests/system_tests/psyclone/test_psyclone_system_test.py
> +        mock_transformation_script = mock.create_autospec(dummy_transformation_script, return_value=Path(__file__))
Yes, I am learning here as well - it's very handy once you get your head around :)

2024-05-15 00:19 UTC, hiker commented on source/fab/steps/psyclone.py
> +    return analysed_x90, all_kernel_hashes
Yes, that's great that you maintained the documentation, thanks!

2024-05-15 00:20 UTC, hiker commented on docs/source/writing_config.rst
> +            You can pass in kernel file roots to `kernel_roots`, a function to get transformation script to
I had some issues with the documentation, and pushed a small change to your branch to fix up the layout.

2024-05-15 00:23 UTC, hiker commented on run_configs/lfric/atm.py
> +    if global_transformation_script:
Ah, your idea is actually interesting, a totally different approach from the existing LFRic way. Please keep this in mind, it might be a nice alternative for implementing this, which will be similar (or even identical) to the handling of paths. I believe your way as well as the current LFRic way can both be implemented with your scripting approach, so that's great.

2024-05-15 00:27 UTC, hiker approved these changes
Hi, thanks for addressing my comments. Great job, a big step forward for Fab.

2024-05-15 00:27 UTC, merged