3 better compiler support
hiker/fab pull request #21
Opened 2024-05-15 04:27 UTC by hiker

That should be ready for a first look.

Hmm - one issue is that git detects (correctly) that there will be conflicts with your changes. But I will only merge your changes in once they have been accepted by Matthew, otherwise I will risk resolving all the conflicts again :(

2024-05-24 09:40 UTC, jasonjunweilyu requested changes
Hi @hiker , I have just finished reviewing this pull request with some minor comments, mainly for typos and clarifications. Thanks for your incredible efforts: 77 files changed with 79 commits and more than 5000 lines changed! Now Fab is in a much better shape to suit the needs of building LFRic and UM.

2024-05-24 09:40 UTC, jasonjunweilyu commented on docs/source/site-specific-config.rst
> +    # Assume the MpiF90 class as shown in the previous example
Here MpiF90 seems not used.

2024-05-24 09:40 UTC, jasonjunweilyu commented on docs/source/site-specific-config.rst
> +    tool_box.add(ifort)
Should be `tool_box.add_tool(ifort)`?

2024-05-24 09:40 UTC, jasonjunweilyu commented on docs/source/site-specific-config.rst
> +    tool_box.add(c_comp)
Should be `tool_box.add_tool(c_comp)`?

2024-05-24 09:40 UTC, jasonjunweilyu commented on docs/source/site-specific-config.rst
> +
Maybe give an example like:

`tool_box = ToolBox()`
`default_c_compiler = tool_box.get_tool(Categories.C_COMPILER)`

2024-05-28 23:08 UTC, hiker commented on source/fab/build_config.py
I don't see that, nor do I see any parsed_args ... anywhere.

2024-05-29 00:00 UTC, jasonjunweilyu commented
I checked this again. You are right. I was looking at the master branch when writing this. Sorry for this.
________________________________
From: Joerg Henrichs ***@***.***>
Sent: Wednesday, 29 May 2024 9:09
To: hiker/fab ***@***.***>
Cc: Junwei Lyu ***@***.***>; Review requested ***@***.***>
Subject: Re: [hiker/fab] 3 better compiler support (PR #21)


@hiker commented on this pull request.

________________________________

On source/fab/build_config.py<https://github.com/hiker/fab/pull/21#discussion_r1617979790>:

I don't see that, nor do I see any parsed_args ... anywhere.

—
Reply to this email directly, view it on GitHub<https://github.com/hiker/fab/pull/21#discussion_r1617979790>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BGRTAAKQH4BZHQ67RQ4CPMTZEUFBHAVCNFSM6AAAAABHXLSIO2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAOBTHE4DCMRXG4>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-05-29 00:17 UTC, hiker commented on source/fab/tools/flags.py
> +            if has_parameter and flag[:flag_len] == remove_flag:
I have changed the description to make it clear that you can only specify a flag without a parameter - i.e. `remove_flag="-J/tmp"` will not work (well, it will only work if the flags do contain `[..., "-J/tmp"]`, but not `"[..., -J", "/tmp"]`.

I am not certain if we need this. Atm this function (which I basically moved from a stand-alone function to a method of this object) is only used to remove flags of which there can be only one (e.g. to indicate where modules are written - they can only be written at one location. It means we don't need to worry about ordering our flags :)

If you have a case of removing a certain flag with a certain parameter, best open a ticket. We would need to take two arguments (flag and parameter), and then also check if there is a combined entry. That sounds doable :)

2024-05-29 00:52 UTC, jasonjunweilyu commented on source/fab/build_config.py
I checked this again. You are right. I was looking at the master branch when writing this. Sorry for this.

2024-05-29 05:48 UTC, hiker reviewed
Submitting the first half of my comments :)

2024-05-29 05:48 UTC, hiker commented on docs/.gitignore
> +build
Done.

2024-05-29 05:48 UTC, hiker commented on docs/source/site-specific-config.rst
> +:class:`~fab.tools.compiler.icc`. Typically, they can just be
Done.

2024-05-29 05:48 UTC, hiker commented on docs/source/site-specific-config.rst
> +    tr.add(MpiF90)   # the tool repository will create the instance
Done. I've opened #23 to add 'doctest'-ing the documentation, we do this in PSyclone and that would really help automatically detecting this kind of error. Thanks to be extra thorough here :)

2024-05-29 05:48 UTC, hiker commented on docs/source/site-specific-config.rst
> +    # Assume the MpiF90 class as shown in the previous example
Indeed.

2024-05-29 05:48 UTC, hiker commented on docs/source/site-specific-config.rst
> +    tool_box.add(ifort)
Yes :(

2024-05-29 05:48 UTC, hiker commented on docs/source/site-specific-config.rst
> +    tool_box.add(c_comp)
Yes.

2024-05-29 05:48 UTC, hiker commented on docs/source/site-specific-config.rst
> +
Good idea.

2024-05-29 05:48 UTC, hiker commented on pyproject.toml
> +    "tests-old",
Good point, we don't :)

2024-05-29 05:48 UTC, hiker commented on source/fab/artefacts.py
Good catch (and I'd guess mypy didn't report this since ArtefactStore is a dict). There was one other file that needed it as well, can't remember which one now.

2024-05-29 05:48 UTC, hiker commented on source/fab/cli.py
Gee, that one is/was a pain :(  This is needed because they linked a Fortran program with the c compiler, so they hard-coded a Gnu-only solution. I have improved this somewhat - it now properly uses the ToolBox to use the linker associated with the compiler (i.e. if compiler is `gfortran`, it will use `linker-gfortran`, and same for Intel). So this way at least the hard-coded gnu option is gone (though there is no support to actually change the compiler to intel).

I did test it with intel (adding a `set_vendor("intel")`) ... and that caused a failure in an interoperability example: if the main program is in C, but you link with ifort, you need to add the option `-nofor-main`. I couldn't find an easy way to support this (unless hard-coding a test if the intel compiler is used to add this flag to the linker). It works as good as before, so I think that's good enough for now.

2024-05-29 05:48 UTC, hiker commented on source/fab/cli.py
Oh, I also added comments to cli.py and test_zero_config (which would trigger the error if intel is used), and I replaced the setting of environment variable to force gnu usage in test_zero-config with the `set_vendor()` call.

2024-05-29 07:03 UTC, hiker commented on tests/unit_tests/steps/test_compile_fortran.py
Indeed.

2024-05-29 08:59 UTC, hiker commented
Gee, fixing mypy involved some major changes to the import order :(  But it should now really be ready for review.

Please check my merging of your "transformation script function" changes, that was a bit hairy :(

2024-05-29 13:29 UTC, hiker commented on source/fab/build_config.py
Ahh, I feel better now :) I'll resolve this conversationthen.

2024-05-30 09:28 UTC, jasonjunweilyu approved these changes
Hi @hiker , thanks for addressing all the review comments. Now I think this can be merged into `bom_master`.

2024-05-30 21:51 UTC, jasonjunweilyu commented
Oops! @hiker , after rebuilding the container and running the Gitlab pipeline of your Gitlab merge request, there seems to be a circular import error with running `grab_lfric.py`. It imports BuildConfig, which initializes the tools and in tool PSyclone, there is a call to import BuildConfig. The error message is attached below (https://git.nci.org.au/bom/ngm/lfric/lfric_atm-fab/-/jobs/67568):

Start grabbing the lfric sources
Traceback (most recent call last):
  File "....../fab_framework/infrastructure/build/fab/grab_lfric.py", line 10, in <module>
    from fab.build_config import BuildConfig
  File "/opt/mamba/envs/container/lib/python3.11/site-packages/fab/build_config.py", line [26](https://git.nci.org.au/bom/ngm/lfric/lfric_atm-fab/-/jobs/67568#L26), in <module>
    from fab.tools.categories import Categories
  File "/opt/mamba/envs/container/lib/python3.11/site-packages/fab/tools/__init__.py", line 16, in <module>
    from fab.tools.psyclone import Psyclone
  File "/opt/mamba/envs/container/lib/python3.11/site-packages/fab/tools/psyclone.py", line 13, in <module>
    from fab.build_config import BuildConfig
ImportError: cannot import name 'BuildConfig' from partially initialized module 'fab.build_config' (most likely due to a circular import) (/opt/mamba/envs/container/lib/python3.11/site-packages/fab/build_config.py)

2024-06-03 00:10 UTC, merged