3 better compiler support
hiker/fab pull request #26
Opened 2024-06-06 00:27 UTC by hiker

An extension of this PR (my apologies, but I want to keep this branch for merging into metomi master).

Fixes issues in run_configs (including some flake8 errors, now run_configs can be "flake8'ed"

2024-06-06 11:11 UTC, jasonjunweilyu requested changes
Hi @hiker , I have tested the changes to the run_configs. There are more build environment and old version code problems than FAB issues. For FAB, it is mainly removing the `linker` argument, updating psyclone_transformation_script part (my fault), and adding a missing `compiler.name`.

2024-06-06 11:11 UTC, jasonjunweilyu commented on run_configs/um/build_um.py
Also failed at the link stage, potentially because of the build environment:

/usr/bin/ld: $FAB_WORKSPACE/um_atmos_safe_vn12.1_gfortran_1stage/build_output/um_main.a(ls_cld.89a237790.o): undefined reference to symbol 'acos@@GLIBC_2.2.5'
/lib64/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

2024-06-07 00:35 UTC, hiker reviewed
Most issues addressed, outstanding issues are tackled in separate ticket.

2024-06-07 00:35 UTC, hiker commented on run_configs/build_all.py
Agreed, that is an ongoing problem, which I think we should tackle properly once we improve compiler flag support. ATM I think the scripts often assume a certain setup (hard-coded mpifort??). I will open a ticket to fix all examples properly ... and that might mean that we port our LFRic build base class as a new baseclass here, and inherit from it in all examples.

Then this base class can properly check which compiler is available, select the right linker  etc.

2024-06-07 00:35 UTC, hiker commented on run_configs/jules/build_jules.py
Linker removed, and the grab_prebuild from a non-existing folder as well. I'll postpone the linking issue till later

2024-06-07 00:35 UTC, hiker commented on run_configs/lfric/atm.py
Done ... and no, the reviewer missed that :)

2024-06-07 00:35 UTC, hiker commented on run_configs/lfric/atm.py
Done.

2024-06-07 00:35 UTC, hiker commented on run_configs/lfric/grab_lfric.py
Again, I'll postpone this for later, when we fix up all examples and move to latest lfric (i.e. after split).

2024-06-07 00:35 UTC, hiker commented on run_configs/lfric/gungho.py
Yes, indeed - that's a bug in this old lfric version (which is not compatible with psyclone 2.5). Again, ignoring for now.

2024-06-07 00:35 UTC, hiker commented on run_configs/lfric/gungho.py
Done, thanks.

2024-06-07 00:35 UTC, hiker commented on run_configs/lfric/gungho.py
Done.

2024-06-07 00:35 UTC, hiker commented on run_configs/lfric/mesh_tools.py
Postponed.

2024-06-07 00:35 UTC, hiker commented on run_configs/um/build_um.py
Good catch, done.

2024-06-07 00:35 UTC, hiker commented on run_configs/um/build_um.py
Postponed.

2024-06-07 00:38 UTC, hiker commented
I think I have fixed all that could easily be fixed, updating lfric, and proper support for linking with different compilers etc to be postponed, see #27 for  tracking this.

2024-06-07 00:50 UTC, jasonjunweilyu approved these changes
Hi @hiker , thanks for fixing the issues. I think now this is good to merge.

2024-06-07 00:51 UTC, merged