Add standard artefacts
hiker/fab pull request #28
Opened 2024-06-07 02:47 UTC by hiker

Replaces all strings as artefacts to enums. Users can still use strings if they need to create their own artefact sets.

2024-06-07 02:55 UTC, hiker commented
Turns out I had to merge in bom_master to get git to properly detect that the changes to run_config are already there.

This PR replaces the strings defined in constant.py for artefact collections with enums in ArtefactSet - it esp. replaces the string constant `"all_source"` that is used. Otherwise it does a bit of additional cleanup. It looks big, but it is mostly change to imports (instead of constants.py the new ArtefactSet enum comes from artefact.py), and then replacing them where they are used. There is still one or two left for things that interact with e.g. the LFRic-specific configurator, but this will all properly be changed in the next PR.

2024-06-19 01:21 UTC, jasonjunweilyu requested changes
Hi @hiker , I have finished my review and thanks for adding `ArtefactSet`. There are just some small comments and then this is ready to be merged.

2024-06-19 01:21 UTC, jasonjunweilyu commented on source/fab/artefacts.py
> +            if artefact == ArtefactSet.OBJECT_FILES:
Is `ArtefactSet.Build_TREES` also a dictionary by default? This should not matter, as `ArtefactSet.Build_TREES` is reset when used by `steps/analyse.py`.

2024-06-19 23:43 UTC, hiker commented
Ready for next review.

2024-06-20 00:24 UTC, jasonjunweilyu approved these changes
Thanks. I think now this is ready to be merged.

2024-06-20 00:24 UTC, merged