Improve artefact workflow
hiker/fab pull request #29
Opened 2024-06-12 23:33 UTC by hiker

This needs to go in after PR #28. It now uses the new enums consistently (i.e. if files are pre-processed, the .F90 files are removed and replaced with the pre-processes .f90 files), so at any stage the C/FORTRAN_BUILD_FILES contains all source files a step needs to look at.

I also updated the run_configs, esp. lfric_common now does NOT create files in `source` anymore, these files are now created in `build/configuration` (and similarly automatically added to the F90_BUILD_FILES)

2024-06-19 23:31 UTC, hiker commented
Here some comments from the code review in #28, which are likely addressed here:
> Would there be any scenario where we don't have any #include or #ifdef directives in the code for preprocessing, therefore not having the preprocessing step and ArtefactSet.FORTRAN_BUILD_FILES collection in ArtefactStore? In this case, do we still need SuffixFilter(ArtefactSet.ALL_SOURCE, '.f90')?

2024-06-19 23:38 UTC, hiker reviewed
OK, all done (or postponed for #29).
Thanks for the review

2024-06-20 10:28 UTC, hiker commented
This kind of finishes the previous PR: the previous PR introduced the enums, here they will now be used consistently, which removes many of the hand-coded (i.e. string-based) artefact names, and relies on the build-in only. I've kept the string-based artefacts, in case any other tool/script/... might need them, but all standard tools should now rely only on these pre-defined artefact sets.

2024-06-24 03:02 UTC, jasonjunweilyu requested changes
Thanks for this. I only have some minor comments. Then I think this can be merged into `bom_master`.

2024-06-24 03:36 UTC, hiker reviewed
Easy one are done, now back to the rest :)

2024-06-24 03:36 UTC, hiker commented on docs/source/writing_config.rst
> +will be added to ``FORTRAN_BUILD_FILES``). A user script can adds its own
Done

2024-06-24 03:36 UTC, hiker commented on docs/source/writing_config.rst
> +3. If :func:`~fab.steps.c_pragma_injector.c_pragma_injector` is being called, it will handle all files in ``C_BUILD_FILES``, and will replace all the original C files with the newly created ones.
Good point, you changed my mind (imho PRAGMAD_C etc should all just go, but I wasn't certain if there are other use cases, so I left them in). I add them into the docs as 'to maintain backward compatibility').

2024-06-24 03:36 UTC, hiker commented on docs/source/writing_config.rst
> +4. If :func:`~fab.steps.preprocess.preprocess_c` is called, it will preprocess all files in ``C_BUILD_FILES`` (at this stage typically preprocess the files in the original source folder, writing the
OK.

2024-06-24 03:36 UTC, hiker commented on docs/source/writing_config.rst
> +11. If :func:`~fab.steps.link.link_exe` is called, it will either use ``OBJECT_ARCHIVES``, or if this is empty ``OBJECT_FILES``, create the binaries, and add them to ``EXECUTABLES``.
Done.

2024-06-24 03:36 UTC, hiker commented on source/fab/artefacts.py
>          '''
Oops.

2024-06-24 03:36 UTC, hiker commented on source/fab/steps/preprocess.py
> +    else:
👍

2024-06-24 03:36 UTC, hiker commented on source/fab/steps/preprocess.py
Done.

2024-06-24 03:36 UTC, hiker commented on source/fab/steps/psyclone.py
>  DEFAULT_SOURCE_GETTER = CollectionConcat([
Good catch.

2024-06-24 03:36 UTC, hiker commented on tests/unit_tests/test_artefacts.py
> +    artefact_store.update_dict(ArtefactSet.OBJECT_FILES, "a", ["AA"])
I've changed it to Iterable.

2024-06-24 03:51 UTC, hiker commented on source/fab/steps/preprocess.py
>      config.artefact_store.copy_artefacts(ArtefactSet.PREPROCESSED_FORTRAN,
I believe you are right, good catch!

2024-06-24 03:51 UTC, hiker commented on source/fab/steps/preprocess.py
>      config.artefact_store.copy_artefacts(ArtefactSet.PREPROCESSED_C,
Ditto.

2024-06-24 04:28 UTC, hiker commented on tests/unit_tests/test_artefacts.py
I tried to fix that quickly, but ran into a few problems. I've added this to #31. I'll suggest we do this separately (and maybe even across more tests, since it looks only some (very few??) tests actually check types.

Well, I have updated the tests to use Path, and the artefact functions to accept str or path, but we need to look at #31 (since as shown a string will actually cause a failure when using suffix)

2024-06-24 04:29 UTC, hiker commented
Ready for next review.

2024-06-24 04:49 UTC, jasonjunweilyu approved these changes
Thanks. I think this is now ready to be merged. I am merging this now.

2024-06-24 04:50 UTC, merged