Make Fab more useable for other codes
hiker/fab pull request #30
Opened 2024-06-20 10:34 UTC by hiker

Besides making the PSyclone API configurable, it also allows to use no-API, which is the future way in PSyclone to use the former 'NEMO' API, i.e. transformation of existing Fortran codes.

Additionally, it adds support for .f/.F files.

2024-06-24 07:11 UTC, jasonjunweilyu requested changes
Hi @hiker , thanks for this. I have finished the review. Only two minor comments. Should the api name be updated from `dynamo0.3` to `lfric` now?

2024-06-24 07:11 UTC, jasonjunweilyu commented on tests/unit_tests/steps/test_psyclone_unit_test.py
> +            api="dynamo0p3",
I think this `dynamo0p3` is a typo? But since `_gen_prebuild_hash` does not need `mp_payload.api`, this does not matter really. Should we make `api` in `class MpCommonArgs` in `steps/psyclone.py` optional then?

2024-06-25 14:14 UTC, hiker commented on run_configs/lfric/atm.py
> +            api="dynamo0.3",
Since even current PSyclone (unofficially, i.e. it's not document or shown on the help page) the old names (dynamo0.3 and gcoean1.0), I've changed all APIs to the old names, so Fab works with PSyclone 2.5.0

2024-06-25 14:54 UTC, hiker commented on tests/unit_tests/steps/test_psyclone_unit_test.py
> +            api="dynamo0p3",
Indeed (well, dynamo0p3 is the PSyclone internal name used for directories). Fixed.

Re the other thing: good point. After a lot of thinking, I've decided to go in the opposite direction: I've added the API to the checksum for PSyclone file (since it already had all command line arguments). While the APIs are not compatible (PSyclone with gocean as API will not be able to read an LFRic file), it really can't hurt and is cleaner.

2024-06-25 15:02 UTC, hiker commented
Ready for next review.

2024-06-26 00:12 UTC, jasonjunweilyu requested changes
Hi @hiker , thanks for updating this. Having the API in hash checksum is great. We probably still need a small test for testing that changing the API would change the checksum. And then this is ready to be merged into `bom_master`.

2024-06-26 00:12 UTC, jasonjunweilyu commented on tests/unit_tests/steps/test_psyclone_unit_test.py
We may need a `def test_api` to test that changing the api should change the hash, to be consistent with `def test_test_file_hash`, `def test_trans_script`, etc. And I just noticed that Line 67 `def test_kernal_deps` has a typo, and should be `def test_kernel_deps`.

2024-07-01 00:13 UTC, jasonjunweilyu approved these changes
Thanks @hiker , I think now this is ready to be merged into `bom_master`.

2024-07-01 00:15 UTC, merged